version: 0.2

env:
  variables:
    PYTHON_VERSION: "3.10"

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - echo "Installing dependencies..."
      - python --version
      - pip install --upgrade pip
      - pip install -r requirements.txt

  pre_build:
    commands:
      - echo "Running pre-build checks..."
      - pip install flake8 pytest
      - echo "Linting code..."
      - flake8 . || echo "Lint warnings found"

  build:
    commands:
      - echo "Running tests..."
      - pytest || echo "No tests found, skipping"
      - echo "Starting FastAPI app for smoke test..."
      - uvicorn app:app --host 0.0.0.0 --port 8000 &
      - sleep 10
      - curl http://localhost:8000 || echo "API endpoint not exposed"

  post_build:
    commands:
      - echo "Build completed successfully on `date`"

artifacts:
  files:
    - '**/*'
